if(NOT DEFINED ANALYZER)
  message(FATAL_ERROR "ANALYZER executable was not provided")
endif()

set(positive "${CMAKE_CURRENT_BINARY_DIR}/yaw_positive.jsonl")
set(negative "${CMAKE_CURRENT_BINARY_DIR}/yaw_negative.jsonl")
set(reverse "${CMAKE_CURRENT_BINARY_DIR}/yaw_reverse.jsonl")
file(WRITE "${positive}" "")
file(WRITE "${negative}" "")
file(WRITE "${reverse}" "")

foreach(index RANGE 0 1200)
  math(EXPR time_us "${index} * 1000")
  math(EXPR phase "${index} % 100")
  math(EXPR delayed_index "${index} - 50")
  math(EXPR delayed_phase "(${delayed_index} + 1000) % 100")
  math(EXPR reverse_delayed_index "${index} - 52")
  math(EXPR reverse_delayed_phase "(${reverse_delayed_index} + 1000) % 100")

  if(phase GREATER 50)
    math(EXPR command_value "50 - ${phase}")
  else()
    set(command_value "${phase}")
  endif()
  if(delayed_phase GREATER 50)
    math(EXPR feedback_value "50 - ${delayed_phase}")
  else()
    set(feedback_value "${delayed_phase}")
  endif()
  if(reverse_delayed_phase GREATER 50)
    math(EXPR reverse_feedback_value "50 - ${reverse_delayed_phase}")
  else()
    set(reverse_feedback_value "${reverse_delayed_phase}")
  endif()

  math(EXPR negative_command_value "-${command_value}")
  math(EXPR negative_feedback_value "-${feedback_value}")
  file(APPEND "${positive}" "{\"time_us\":${time_us},\"data\":{\"plan_yaw\":${command_value},\"gimbal_yaw\":${feedback_value},\"plan_mode\":1}}\n")
  file(APPEND "${negative}" "{\"time_us\":${time_us},\"data\":{\"plan_yaw\":${negative_command_value},\"gimbal_yaw\":${negative_feedback_value},\"plan_mode\":1}}\n")
  file(APPEND "${reverse}" "{\"time_us\":${time_us},\"data\":{\"plan_yaw\":${command_value},\"gimbal_yaw\":${reverse_feedback_value},\"plan_mode\":1}}\n")
endforeach()

execute_process(
  COMMAND "${ANALYZER}" --positive "${positive}" --negative "${negative}" --reverse "${reverse}"
  RESULT_VARIABLE analyzer_result
  OUTPUT_VARIABLE analyzer_output
  ERROR_VARIABLE analyzer_error)
file(REMOVE "${positive}" "${negative}" "${reverse}")

if(NOT analyzer_result EQUAL 0)
  message(FATAL_ERROR "analyzer failed (${analyzer_result}): ${analyzer_error}")
endif()
if(NOT analyzer_output MATCHES "yaw_delay_curve:")
  message(FATAL_ERROR "analyzer did not output a yaw delay curve: ${analyzer_output}")
endif()
if(NOT analyzer_error MATCHES "\\(positive\\): delay=50")
  message(FATAL_ERROR "analyzer did not recover 50 ms positive delay: ${analyzer_error}")
endif()
if(NOT analyzer_error MATCHES "\\(negative\\): delay=50")
  message(FATAL_ERROR "analyzer did not recover 50 ms negative delay: ${analyzer_error}")
endif()
if(NOT analyzer_error MATCHES "\\(reverse\\): delay=5[12]")
  message(FATAL_ERROR "analyzer did not recover 52 ms reversal delay: ${analyzer_error}")
endif()
if(NOT analyzer_output MATCHES "yaw_reverse_penalty: 0\\.002")
  message(FATAL_ERROR "analyzer did not recover 2 ms reversal penalty: ${analyzer_output}")
endif()
