pattern_cols: 9      # 棋盘格每行的内角点数（格子数-1）
pattern_rows: 6      # 棋盘格每列的内角点数（格子数-1）
square_size_mm: 40   # 棋盘格方块大小（毫米）

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 4000
gain: 10.0
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
# com_port: "/dev/ttyACM0"