enemy_color: "red"
# enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: trt_0708
classify_model: ../assets/tiny_resnet.onnx
yolo11_model_path: ../assets/yolo11.xml
yolov8_model_path: ../assets/yolov8.xml
yolov5_model_path: ../assets/yolov5.xml
tensorrt_engine_path: ../assets/0708_fp16_super.engine
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 1280
image_height: 720

fov_h: 57.7 #87.7
fov_v: 56.7 


new_fov_h: 63.133 #67
new_fov_v: 75.0484
usb_frame_rate: 120
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
# camera_name: "hikrobot"
# exposure_us: 2000
# gain: 16.9
# vid_pid: "2bdf:0001"
# flip: false
# mirror: false

camera_name: "daheng"
camera_sn: "FDN24040487"
exposure_us: 5000
gain: 0.5
gamma: 0.7
vid_pid: "2bdf:0001"
flip: false
mirror: false
timestamp_offset_us: 1000 #us

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

number_classifier:
  model_path: "../assets/rv_model/mlp.onnx"   # 模型路径 (确保文件存在)
  label_path: "../assets/rv_model/label.txt"  # 标签文件路径
  threshold: 0.5                 # 数字分类阈值
  ignore_classes: ["negative"]   # 忽略的类别

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 25
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -2.0 # degree -2.5
pitch_offset: -4.7  # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
left_yaw_offset: -1
right_yaw_offset: -0.6
decision_speed: 10 # rad/s
high_speed_delay_time: 0.26 # s
low_speed_delay_time: 0.25 # s

#####-----shooter参数-----#####
first_tolerance: 5 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----planner-----#####
fire_thresh: 0.003 # 
small_armor_tolerance: 0.12
big_armor_tolerance: 0.22
gimbal_control_delay: 0
tower_pitch_prediction_time: 0.05

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6,0]
R_pitch: [1]

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]

# 重投影误差: 0.1374px
camera_matrix: [3463.7701919588485, 0, 680.43669894383868, 0, 3450.3152115133189, 694.32610333730372, 0, 0, 1]
distort_coeffs: [-0.0094903762961805541, -0.10983451974022652, 0.0067729760529102474, 0.0046422730249848871, 2.7718267775770777]

# 相机同理想情况的偏角: yaw-3.23 pitch1.67 roll-0.20 degree
R_camera2gimbal: [0.05616961400956666, 0.02920234427776968, 0.99799408693173064, -0.9984153408019103, -0.0017935384096012807, 0.05624580403353209, 0.0034324500610342138, -0.99957191152445646, 0.029055326154125538]
t_camera2gimbal: [0.27105015504526542, 0.10053004506772954, -0.14559443254888874]


com_port: "/dev/ttyUSB0"
# 陀螺仪是否装错, 编号012分别代表电控坐标系ypr，想换旋转轴只需要对编号进行互换即可，负号就是对当前值取负，交换完再取负
# 上车前记得对齐电控坐标系和济瞄惯性系
gimbal_y1: 1
gimbal_p2: 2
gimbal_r3: -3
