# enemy_color: "auto"
enemy_color: "blue"
# enemy_color: "red"


#####-----神经网络参数-----#####
yolo_name: trt_0526
classify_model: ../assets/tiny_resnet.onnx
yolo11_model_path: ../assets/yolo11.xml
yolov8_model_path: ../assets/yolov8.xml
yolov5_model_path: ../assets/yolov5.xml
tensorrt_engine_path: ../assets/0708_fp16_super.engine
tensorrt_engine_path_0526: ../assets/0526.engine
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 1280
image_height: 720

fov_h: 57.7 #87.7
fov_v: 56.7 


new_fov_h: 63.133 #67
new_fov_v: 75.0484
usb_frame_rate: 120
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
# camera_name: "hikrobot"
# exposure_us: 2000
# gain: 16.9
# vid_pid: "2bdf:0001"
# flip: false
# mirror: false

camera_name: "hikrobot"
camera_sn: "DA7188471"
exposure_us: 6000
gain: 0.7
gamma: 0.7
vid_pid: "2bdf:0001"
flip: false
mirror: false
timestamp_offset_us: 1000 #us

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

number_classifier:
  model_path: "../assets/rv_model/mlp.onnx"   # 模型路径 (确保文件存在)
  label_path: "../assets/rv_model/label.txt"  # 标签文件路径
  threshold: 0.5                 # 数字分类阈值
  ignore_classes: ["negative"]   # 忽略的类别

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 25
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 2.2 # degree -2.5
pitch_offset: -1.8  # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
left_yaw_offset: -1
right_yaw_offset: -0.6
decision_speed: 10 # rad/s
high_speed_delay_time: 0.025 # s
low_speed_delay_time: 0.020 # s

#####-----shooter参数-----#####
first_tolerance: 5 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----planner-----#####
fire_thresh: 3 # 
target_dist_error: 0
target_h_error: -0.20
small_armor_tolerance: 0.12
big_armor_tolerance: 0.22
gimbal_control_delay: 0.012
tower_pitch_prediction_time: 0.05

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6,0]
R_pitch: [1]

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]

# 重投影误差: 0.0600px
camera_matrix: [3629.2604024723614, 0, 615.76296028559454, 0, 3617.5424611963276, 537.28249377915051, 0, 0, 1]
distort_coeffs: [-0.0064563365740047977, 0.26597520888340187, -0.00091608724392189006, -0.0084950810347407466, -0.87748546654082848]

# 相机同理想情况的偏角: yaw0.37 pitch1.64 roll-2.29 degree
R_camera2gimbal: [-0.0075966848382389429, 0.028332439342095388, 0.99956968904643917, -0.99917500836468665, -0.040094976336004562, -0.0064572077590568473, 0.039894774581351655, -0.99879410578634353, 0.028613654215451589]
t_camera2gimbal: [-0.0064300910580854069, 0.037276498186262115, -0.055090648902732367]


com_port: "/dev/ttyUSB0"
# 陀螺仪是否装错, 编号012分别代表电控坐标系ypr，想换旋转轴只需要对编号进行互换即可，负号就是对当前值取负，交换完再取负
# 上车前记得对齐电控坐标系和济瞄惯性系
gimbal_y1: 1
gimbal_p2: 2
gimbal_r3: 3
