# enemy_color: "red"
enemy_color: "red"

#####-----神经网络参数-----#####
yolo_name: yolov8
classify_model: ../assets/tiny_resnet.onnx
yolo11_model_path: ../assets/yolo11.xml
yolov8_model_path: ../assets/yolov8.xml
yolov5_model_path: ../assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 11
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -0.3 # degree -2.5
pitch_offset: 2.7 # degree 2
comming_angle: 50 # degree
leaving_angle: 0 # degree
decision_speed: 8 # rad/s
high_speed_delay_time: 0.017 # s
low_speed_delay_time: 0.017 # s
gimbal_delay: 0.002
shoot_offset: 2

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
camera_sn: "DA9492714"
exposure_us: 6000
gain: 0.7
vid_pid: "2bdf:0001"
flip: true
mirror: true
timestamp_offset_us: 2000 #us

# camera_name: "daheng"
# camera_sn: "FDN24040486"
# exposure_us: 3000
# gain: 0.5
# gamma: 0.7
# vid_pid: "2ba2:4d55"
# flip: true
# mirror: true
# timestamp_offset_us: 2000 #us

# -1  0  0
#  0 -1  0
#  0  0  1
# R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]
R_gimbal2imubody: [-1, 0, 0, 0, -1, 0, 0, 0, 1]

# 相机同理想情况的偏角: yaw-1.28 pitch-0.86 roll1.69 degree
# 标定板到世界坐标系原点的水平距离: 2.32 m
# 标定板同竖直摆放时的偏角: yaw33.35 pitch3.18 roll178.77 degree
R_camera2gimbal: [0.021855625413864842, -0.015647731914552505, 0.9996386747838935, -0.9993256618827006, 0.029166648211860085, 0.022305338705964458, -0.029505137526726087, -0.9994520774494474, -0.01499972471457684]
t_camera2gimbal: [0.17084305749157316, -0.04075354126954691, 0.029940249686494804]
# 重投影误差: 0.0855px
camera_matrix: [2368.6535582332217, 0, 709.5986018632645, 0, 2367.2059390988875, 557.3218862700319, 0, 0, 1]
distort_coeffs: [-0.03490547533857166, 0.23879749900556682, 0.0018315902205457042, 0.00031464218053409257, -0.30716218266668555]
# _camera2gimbal第一位调yaw
# _camera2gimbal第二位调yaw
# _camera2gimbal第三位调pitch
#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/ttyACM0"
# 陀螺仪是否装错, 编号012分别代表电控坐标系ypr，想换旋转轴只需要对编号进行互换即可，负号就是对当前值取负，交换完再取负
# 上车前记得对齐电控坐标系和济瞄惯性系
gimbal_y1: 1
gimbal_p2: 3
gimbal_r3: -2
# 济瞄的惯性系  z轴往上, x轴是枪管指向
#     x  z
#      \ |
#       \|
# y_ _ _ 0   z:yaw   x:roll   y:pitch

#####-----planner-----#####
target_dist_error: -0.23
target_h_error: 0.28
fire_thresh: 0.003
small_armor_tolerance: 0.12
big_armor_tolerance: 0.22
tower_and_base_armor_tolerance_: 0.10  # 26赛季前哨站和基地装甲板检测宽度
gimbal_control_delay: 0.022 #0.08
tower_pitch_prediction_time: 0.05

max_yaw_acc: 80
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6,0]
R_pitch: [1]

#####-----buff_detector参数-----#####
# rm_buff_detector 红蓝通道差分阈值
color_thresh: 140
auto_color_thresh: true
color_thresh_min: 35
color_thresh_max: 140
color_thresh_alpha: 0.2
color_thresh_max_step: 4
min_foreground_ratio: 0.0001
max_foreground_ratio: 0.15
auto_thresh_use_roi: true
auto_thresh_roi_scale: 1.35
auto_thresh_roi_min_size: 240

# 绿色预测框参数
prediction_box_time: 0.08
prediction_velocity_alpha: 0.25
prediction_max_angular_speed: 3.0

detect:
  contrast: 1
  brightness: 
    blue: -120
    red: -100
  brightness_threshold:
    blue: 120
    red: 40
  morphology_size:
    blue: 3
    red: 3
  dilate_size: 2
  # canny_low_threshold: 100
  # canny_high_threshold: 180
  # approx_epsilon: 1.0
  R_contours_min_area: 200
  R_contours_max_area: 600
  fanblades_head_contours_min_area: 3000
  fanblades_head_contours_max_area: 8000
  fanblades_body_contours_min_area: 1000
  fanblades_body_contours_max_area: 4000
  standard_fanblade_path: ./assets/standard_fanblade.jpg

model: "../assets/yolo11_buff_int8.xml"
#####-----buff_aimer参数-----#####
aim_time: 0.150         # s
wait_time: 0.300        # s
command_fire_gap: 0.080 # s
fire_gap_time: 0.700   # s
predict_time: 0.120    # s
