set(_AMENT_PACKAGE_NAME "sp_vision")
set(sp_vision_VERSION "1.0.0")
set(sp_vision_MAINTAINER "lzhros <lzhros@example.com>")
set(sp_vision_BUILD_DEPENDS "rclcpp" "std_msgs")
set(sp_vision_BUILDTOOL_DEPENDS "ament_cmake")
set(sp_vision_BUILD_EXPORT_DEPENDS "rclcpp" "std_msgs")
set(sp_vision_BUILDTOOL_EXPORT_DEPENDS )
set(sp_vision_EXEC_DEPENDS "rclcpp" "std_msgs")
set(sp_vision_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(sp_vision_GROUP_DEPENDS )
set(sp_vision_MEMBER_OF_GROUPS )
set(sp_vision_DEPRECATED "")
set(sp_vision_EXPORT_TAGS)
list(APPEND sp_vision_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
